### ISSUE TITLE
Create an actual test suite

### ISSUE THREAD

**Issue by cscheid** [cscheid/rgithub#48]
I've been reluctant to create a test suite because we can't test the entry points that require authentication (and the things that modify state on GitHub itself are even uglier to test). But that shouldn't stop us from doing basic tests.

**Comment by cscheid** [comment]
Here's problem number 1: without authentication, we can only make 60 requests an hour. That's not enough requests to cover all of the GitHub entry points. This means we will only be able to run the test suite authenticated, which makes `R CMD CHECK` super tricky. I've no idea how to do this.

@hadley, @jennybc, any ideas? Sorry to spam, but I'm curious what you think about this.

**Comment by jennybc** [comment]
I do know how to run the test authenticated Even on travis. We're testing as authenticated user all the time over in [`googlesheets`](https://github.com/jennybc/googlesheets). It won't even be as hard for this package since the GitHub API allows personal access tokens (vs OAuth only). It will boil down to encrypting a PAT as an environment variable and then doing your context-creating thing in a file like `tests/testthat/helper01-authenticate.R`, which will put that in place before the remaining tests run.

**Comment by cscheid** [comment]
Closed (wontfix) by #70.
